# Generated by Django 3.1.4 on 2020-12-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_auto_20201226_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='source',
            field=models.CharField(choices=[('ONLINE_SERVICE', 'ONLINE_SERVICE'), ('RENT', 'RENT'), ('SALARY', 'SALARY'), ('TRAVEL', 'TRAVEL'), ('FOOD', 'FOOD'), ('OTHERS', 'OTHERS')], max_length=255),
        ),
    ]
